src/commands.ts

This was using `fsPath` which normalizes for the OS. This should prevent that!
Fixes #21

fix: use the proper path separator

---

package.json
src/storage.ts

@deansheather filed a bug related to the Windows Firewall prompt coming up with every new binary (i.e. every time we download `coder` to an updated version).
After some initial testing, it appears keeping the binary in the same place will make the prompt only appear on the first time.
Previous implementation kept the version in the path.
We decided to refactor things to add support for [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) on the server and then use those changes on the client (aka in the extension).
This means now the client will tell the server "Here's the version I have. What should I do?" and send the appropriate headers.
TBD
Fixes #23

fix: keep binary in same place, update if needed

---

src/commands.ts

fix: open workspaces in new windows

---

src/commands.ts
src/extension.ts
src/remote.ts
yarn.lock

This allows for a magical open-click to open a folder experience!

feat: open an agent-defined directory by default

---

src/remote.ts

This was causing a Windows user troubles!
cc @pcgeek86 thank you for reporting and helping :sunglasses: 
Fixes #67

fix: allow `~` to work when resolving `remote.SSH.configFile` on Windows

---

package.json
src/remote.ts
src/sshConfig.test.ts
src/sshConfig.ts

Allow users to override the default SSH config options, just like the coder cli allows with flags. This affects what is written to `~/.ssh/config`.

feat: Add extension settings for customizing ssh config

---

src/remote.ts
src/sshConfig.ts
src/sshSupport.test.ts
src/sshSupport.ts

Fixes coder/coder#7169, coder/vscode-coder#73.

fix: check if OpenSSH supports `SetEnv`

---

src/remote.ts

fix: resolve odd label formatting for recently opened

---

src/remote.ts
src/sshSupport.test.ts
src/sshSupport.ts

This was reported by a member in Discord, and displayed a poor error by VS Code when it failed before.
Users cannot override our config options otherwise connections may fail or have unexpected behavior.

feat: validate ssh properties before launching workspaces

---

package.json
src/workspacesProvider.ts

Closes #93 
We added  Coder actions to the "Open a Remote Window" menu list.

add coder to the Open a Remote Window list

---

src/workspacesProvider.ts

Fix open workspace from sidebar

fix: open from sidebar with agent

---

package.json
src/WorkspaceAction.ts
src/remote.ts
src/storage.ts
src/workspacesProvider.ts
webpack.config.js
yarn.lock

Opening this PR in place of #110 as this solution is a little cleaner.
This resolves https://github.com/coder/coder/issues/7360

feat: add VS code notifications for workspace actions

---

package.json
src/error.test.ts
src/storage.ts
yarn.lock

Closes #103.
This provides two ways for folks to work around security restrictions where the binary can only be ran from specific directories or has to be signed.  
The former can be worked around by setting the destination, and the latter can be worked around by setting the source and providing signed binaries.
Eventually we should look into providing signed binaries straight from Coder.
I started writing tests, however there are so many VS Code APIs to mock I abandoned the idea.  We should revisit once we switch back to the standard testing framework.

Add binary source and destination settings

---

.eslintrc.json
package.json
src/commands.ts
src/error.ts
src/extension.ts
src/headers.test.ts
src/headers.ts
src/remote.ts
src/sshSupport.test.ts
src/sshSupport.ts
src/storage.ts

The command will be executed before requests and before configuring SSH to set custom headers.
Some notes:
1. When I use `--header` I seem to get the value set twice.  For example if I use `coder --header X-MY-CUSTOM-HEADER=hello-there` then on the server end I see `x-my-custom-header: hello-there, hello-there` so we should look into that.
2. I went with environment variables to pass data to the credentials process for now since I figured that would be easier than parsing command-line arguments but opinions are welcome here.  Only `CODER_URL` right now.  Are there others needed?
3. ~More importantly, I am not sure about the config SSH portion.  Since configuration might only happen on the first connect, the headers we hardcode into the SSH config could expire.~
~I have two main ideas for …

Add customizable header command

---

src/commands.ts
src/extension.ts
src/workspacesProvider.ts

Refresh workspaces when logging in and out

---

src/commands.ts

I think this happens when `detail` is undefined.  I am not sure if `err` itself can be undefined but I accounted for that just in case.
I went with detail, then the error message, then the status code, then a final fallback message.

Fix "undefined" in error message

---

package.json
src/extension.ts

adding configuration properties:
* coder.tlsCertFile
* coder.tlsKeyFile
* coder.tlsCaFile
fixes #126

feat: add options to support client tls

---

package.json

It seems that if you do not use any files in the workspace then you can set this as true.
This fixes an issue where you get "no view is registered with id" because the extension seems to be in a half-activated state where the activate function runs but the view does not exist.  If you check the extension list you see that the extension is disabled due to workspace trust.  It might be a bug in VS Code that only presents when an extension is using the  `onResolveRemoteAuthority:ssh-remote` activation event.
Fixes https://github.com/coder/vscode-coder/issues/134

Mark untrusted workspaces as supported

---

src/sshSupport.test.ts
src/sshSupport.ts

Fixes https://github.com/coder/vscode-coder/issues/108
Still not sure why it reportedly worked before, as I think this code path has always been taken.  Maybe there are certain conditions where parsing the config is skipped but I have not dug deep enough to be sure.
This is still not complete because we are not handling `!`, other characters like `.` should be handled literally, and maybe some other things, but it should resolve the immediate issues.  We might also want to only parse hosts between the start/end block markers rather than the whole config, but I am not sure on that one.

Handle ? in SSH config

---

src/remote.ts
src/version.test.ts
src/version.ts

fix: check for versions greater than 2.3.3 for the log-dir flag

---

src/workspaceAction.ts

Hotfix for 
https://github.com/coder/coder/issues/11652
https://github.com/coder/customers/issues/400
Halves maximum time to display workspace autostop warning notification.

halved notification check for autostop warning

---

src/commands.ts
src/extension.ts

It looks like when we switched to using the VS Code desktop module the URL was no longer included, which caused the extension to query localhost if you had never logged in before, which errors and causes the configuration to never happen.
I will fix the module as well, but I figure we can check the URL in the plugin just in case.  **Edit**: module PR: https://github.com/coder/modules/pull/107
Fixes https://github.com/coder/coder/issues/10896

Ensure we have a URL

---

src/remote.ts

See https://github.com/coder/coder/pull/10473
After this change you can see in the logs:
```
[13:50:25.629] > local-server-1> Running ssh connection command: "-v -T -D 43233 -o ConnectTimeout=1800 coder-vscode--code-asher--dev27--dev bash"
```

Override connect timeout

---

src/commands.ts
src/extension.ts
src/storage.ts

We default to the last used URL or CODER_URL, if set, and you can choose from a list of past URLs.
Closes https://github.com/coder/vscode-coder/issues/182.
In this screenshot the "prefilled" value is from CODER_URL and dev.coder.com is from a past connection.

Add URL history and CODER_URL

---

src/workspacesProvider.ts

While adding an automatic refresh I discovered it was easy to
accidentally cause two refreshes to go off at the same time which causes
some races.
Also added a minor tweak to pass in the URL instead of pulling from the
global state since that felt race-y too.

Prevent parallel refreshes

---

src/extension.ts
src/workspacesProvider.ts

Closes https://github.com/coder/vscode-coder/issues/184.
One existing issue with refreshing that is made more apparent with the auto refresh is that it reestablishes all the agent metadata watchers which both feels wasteful and causes the metadata to flash as it disappears for a moment then comes back when the watcher comes online.  In a followup PR I think I will refactor this to reuse existing watchers when possible.
Stacked on https://github.com/coder/vscode-coder/pull/202.

Automatically refresh workspaces

---

src/api-helper.ts
src/workspacesProvider.ts

Followup PR to reuse watchers to make the automatic refresh less janky.
This has two effects:
1. Lower overhead from establishing the watchers over and over.
2. No more flashing in the tree as the watchers get recreated and we wait for the first update.
I renamed `CoderTreeItemType` to make clear it was for openable items only, not for the metadata items and not for the new error item.
Because I needed to refactor the watchers a little I added a line for when something with the metadata fails, rather than quietly disposing (tested by manually adding `throw new Error("hey")`).

Reuse agent metadata watchers

---

src/sshConfig.test.ts
src/sshConfig.ts

This PR introduces two changes:
1. Replace vscode block in-place in the SSH config
2. Adds an additional guard against replacing user-added blocks that _look_ like an old-form SSH config block (without block markings)
TBH, we could probably remove the old block detection entirely instead of this additional check, but didn't want to make that decision here.

fix: replace ssh config block in-place

---

fixtures/bin.bash
fixtures/bin.old.bash
src/cliManager.test.ts
src/cliManager.ts
src/remote.ts
src/storage.ts

- Add more logging (the main goal of this commit).
- Break out parts specific to the binary and add tests for those parts.
- Check the version before making the request.
- Avoid deleting the old binary right away, mostly to make it possible
to debug why the plugin thought it was invalid.  It will be cleaned up
on the next download, so at most we have one.
- Clean up left-over temporary binaries too.
- Validate downloaded binary.
- Catch error on writing (for example if we are downloading the binary
to a read-only location). 
Related: https://github.com/coder/vscode-coder/issues/193

Improve fetching Coder binary

---

src/extension.ts

Previous MR https://github.com/coder/vscode-coder/pull/221
I have been a dedicated user of both Coder and Cursor. However, I've encountered persistent issues when attempting to connect to the Coder workspace via Cursor ([Cursor](https://cursor.sh/)). These issues range from receiving 404 errors to SSH connection failures, preventing any access to the workspace. The root cause of these problems lies in the necessity to use Cursor's built-in Open Remote - SSH extension, `anysphere.open-remote-ssh`, for successful SSH connections.
I've confirmed that users utilizing Cursor can simply specify `anysphere.open-remote-ssh` explicitly within the Coder plugin without any issues coexisting with `ms-vscode-remote.remote-ssh`. Therefore, I've made a straightforward update to check for the existence …

Enhancing SSH Connection Compatibility with Cursor

---

src/error.ts
src/extension.ts
src/remote.ts

Closes: https://github.com/coder/customers/issues/543
If the template has `require_active_version`, the extension will auto update the workspace on start.
If parameters change, an error like this gets raised:

feat: auto update workspace if required by template

---

CHANGELOG.md
package.json
src/commands.ts
src/error.ts

Closes https://github.com/coder/customers/issues/442
If testing, can use URLs from https://badssl.com (like https://incomplete-chain.badssl.com/).
Tweak error wording and show the detailed error under the input, so it will display in two places now.
Also remove the "view more details" button from the notification, for reasons detailed in the commit message.

Tweak certificate errors

---

package.json
src/storage.ts

Closes https://github.com/coder/vscode-coder/issues/193

Add option to disable downloads

---

CONTRIBUTING.md
src/commands.ts
src/extension.ts

This covers the plugin side of https://github.com/coder/vscode-coder/issues/241.  We will still need to make changes on the module side.

Add openRecent query parameter

---

src/remote.ts

The documentation for the header command setting says:
> The following environment variables will be available to the process: `CODER_URL`.
However, if the command line itself references `$CODER_URL`, when connecting via the VSCode extension the variable will get substituted _before_ the `coder` CLI can set the variable when running the header command, which is contrary to the behaviour of the JetBrains plugin. This is because the VSCode extension is currently writing the header command into the SSH config's `ProxyCommand` with double quotes, allowing the shell spawned by `ssh` to substitute `$CODER_URL` (with the empty string).
This ensures environment variable references within the header command are not substituted before the `coder` binary can receive them, by using single quotes …

fix: escape variables in the header command

---

src/api.ts
src/commands.ts
src/extension.ts
src/remote.ts
src/storage.ts
src/workspaceAction.ts
src/workspacesProvider.ts
yarn.lock

We support connecting to previous workspaces, but sometimes this breaks because the previous workspace belongs to a different deployment, and the plugin always uses the credentials of the current deployment (https://github.com/coder/vscode-coder/issues/173).
This is a first step to fixing that: separating the client into two: one used by the plugin as a whole (mainly used to list workspaces of the current deployment in the sidebar) and one used to connect to a workspace which may belong to a different deployment (which is used to start the workspace, get the version, etc).  Thankfully this is pretty chill since @Parkreiner's changes to Coder core!
For now that second client does still use the global url and token so functionally it is still the same, but I will fix that in a follow up PR …

Refactor REST client

---

src/commands.ts
src/extension.ts
src/remote.ts
src/sshConfig.test.ts
src/sshConfig.ts
src/storage.ts
src/util.test.ts
src/util.ts

This is broadly three parts, as described by the commits, but the main gist is that the SSH blocks are now scoped (with the deployment URL in the host name), and the individual config files referenced in those config blocks are also scoped (with the deployment URL in the directory), and the connection process has been decoupled from the credentials in VS Code's memory and coupled to the credentials in the associated config directory instead.  More context in each commit message; it might even make sense to review by commit.
Existing hosts should not be affected, only new connections will be scoped by deployment.  Existing hosts (ones without the deployment in the host) will continue using the old config block and directories.  But it will not be possible to add new hosts using the old …

Add support for connections to multiple deployments

---

CHANGELOG.md
src/remote.ts
src/workspacesProvider.ts

Closes #261
But...maybe we will want to create a custom webview instead if we need the colors.

Add statuses to sidebar

---

src/headers.test.ts
src/headers.ts

Allow no output from the header command, for parity with the Coder CLI, similarly to the JetBrains plugin in https://github.com/coder/jetbrains-coder/issues/404

Allow empty output from header command

---

CHANGELOG.md
README.md
package.json
src/api.ts
src/error.test.ts
src/remote.ts
src/util.ts

This makes passing the --log-dir option to coder/coder optional and based on whether a proxyLogDirectory is set in the extensions settings.
The reasoning behind this is rather than make a unilateral decision about where and how long to store the logs, we simply give control to the user.

Make log dir optional

---

package.json
src/commands.ts

Two steps:
1. Hide the command
2. Make the command fall back to the regular open if it is somehow called
More details can be found in the commit messages.
Close https://github.com/coder/vscode-coder/issues/341

Remove coder.openFromSidebar from command list

---

package.json
src/api.ts
src/commands.ts
src/extension.ts
src/storage.ts

The strategy: when configuring the cli, write blank token files, since currently the `vscodessh` always expects a file.  Still need to validate if this works; if not we may need to write something like `unused` or modify the cli itself.
We configure in two places: login via command palette and dashboard link, so both those code paths are changed to write `""` when not using token auth.  Additionally, the login route is changed to not prompt for the token (failure to auth will be a hard error instead).

Do not require token auth with mTLS

---

package.json
src/api.ts

This allows using a specific hostname for the TLS connection, this is useful when the tls cert does not match the hostname of the server which can be used for testing.
Not sure how we test this....

feat: add coder.tlsAltHost option

---

src/api.ts
src/remote.ts
src/storage.ts

Replace the REST-API-based start flow with one that shells out to the coder CLI.

Start workspaces by shelling out to CLI

---

src/commands.ts
src/extension.ts

This can be noisy and confusing if login attempts fail for users who don't have Coder accounts.

Suppress login failure dialog on autologin

---

CHANGELOG.md
src/sshSupport.test.ts
src/sshSupport.ts

When validating that our settings are not overridden by a user's ssh config, we were converting host names to regular expressions to use as matchers. In doing so, we were not correctly escaping `.` characters, which are special in regular expressions but not in host names.
This triggered a false flag when using the vscode extension alerting the user they were improperly overriding settings which they were not.
Note: this didn't come up before because we only now started using `coder.` has a host name in the ssh config as part of updating the vscode extension to simply use `coder ssh` as opposed to a dedicated `coder vscodessh` command.

properly escape . in host -> ssh conversion

---

CONTRIBUTING.md
src/commands.ts
src/featureSet.ts
src/remote.ts
src/util.test.ts
src/util.ts

Build on top of recent coder PRs to make `coder ssh` provide equivalent functionality to `vscodessh`, avoiding the need for a VSCode-specific ssh subcommand.
This aligns the VS Code extension with the proposed change to the JetBrains extension in https://github.com/coder/jetbrains-coder/pull/521.
Depends on https://github.com/coder/coder/pull/16078, https://github.com/coder/coder/pull/16080, https://github.com/coder/coder/pull/16088

Use coder ssh in place of coder vscodessh

---

CHANGELOG.md
src/remote.ts

`maybeWaitForRunning` can take indefinitely long because it prompts for confirmation, and in that time, client certificates can expire. Start setup fresh after this call to make sure the REST client uses the latest certificates.

Recreate REST client after starting a workspace

---

CHANGELOG.md
src/remote.ts

This is a followup to #431. It addresses the need to also recreate the REST client used inside `maybeWaitForRunning`, since it makes API calls before returning to `setup`.

Recreate REST client after starting a workspace (part 2)

---

CHANGELOG.md
src/api.ts
src/remote.ts

This causes TLS certificates to be reread on every API request, so if they are refreshed on disk, the extension will pick up the new ones. It also avoids the need to recreating the REST client (which was an ultimately unsuccessful effort to make the extension pick up new certificates).

Remove agent singleton

---

CHANGELOG.md
package.json
src/api-helper.ts
src/api.ts
src/workspaceMonitor.ts
src/workspacesProvider.ts
yarn.lock

This allows client TLS certificates to be used for event monitoring. Upgrade to a newer `eventsource` package that supports a custom `fetch` function, and provide a custom `fetch` function which wraps Axios.

Use Axios client for EventSource

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Document the addition of Windsurf support and clarify that the extension now works with multiple editors beyond VS Code.

docs: document other editor support

---

src/remote.ts

Previously we used the `coder vscodessh` command for the proxy command in the ssh config, which does not have the autostart-on-connect capabilities. This restores the previous behavior.

fix: disable autostart on ssh command

---

src/commands.ts
src/extension.ts
src/util.ts

Relates to https://github.com/coder/coder/issues/16426
Adds the ability to connect to a running devcontainer inside a Coder Workspace.
We add a new handler to handle the URI 
```
vscode://coder.coder-remote/openDevContainer
```
With the following query params:
- `url`: The URL of the deployment
- `token`: The API key
- `owner`: The workspace owner
- `workspace`: The workspace name
- `devContainerName`: The name of the dev container
- `devContainerFolder`: The folder inside the dev container

feat: add ability to attach to devcontainers

---

src/api.ts

We were not passing down the signal to the axios requests, causing them to be alive when they should be closed.
Related to https://github.com/coder/vscode-coder/issues/468

fix: close sse connections

---

src/remote.ts

Relates to https://github.com/coder/vscode-coder/issues/447
Following on from https://github.com/coder/coder/pull/17572, this PR has the extension read the `using_coder_connect` bool from the network stats file, and change the status accordingly.

feat: show if using coder connect in status indicator

---

src/sshConfig.test.ts
src/sshConfig.ts

Relates to https://github.com/coder/vscode-coder/issues/504
To avoid race conditions, write to a tempfile and then rename.
Smoke-tested by:
- Setting immutable flag on `/Users/cian/.ssh/config` (`sudo chflags uchg $PATH`) and validating that the rename failed:
- Setting immutable flag on `/Users/cian/.ssh` and validating that writing the temp file failed:
- Once immutable flag removed (`sudo chflags nouchg $PATH`), connecting to workspace is successful.

fix: SSHConfig: atomically write ssh config

---

src/sshConfig.test.ts
src/sshConfig.ts
src/util.test.ts
src/util.ts

Relates to https://github.com/coder/vscode-coder/issues/504
Ports over the existing checks in `coder config-ssh` to handle malformed blocks.
Now, if your SSH config is malformed, you will see an error similar to the below upon attempting to connect:
* If one of the automatically generated blocks is missing a start or end comment, you will see the below error:
* If there is more than one block with a given label, you will see the below error:
In both cases, it will unfortunately be necessary to edit the SSH config and fix the issue manually.

fix: SSHConfig: check for multiple start/end blocks

---

src/extension.ts

feat: support cursor's new in-house remote ssh extension

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

This PR updates the Node.js version used in CI and release workflows from 18 to 20.
- Ran tests with Node 20 locally and all tests passed
Closes #521

chore: update Node.js version to 20

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Reverts coder/vscode-coder#522
This causes `yarn build` to fail, probably due to some type-checking issues. 
```console
ERROR in /Users/matifali/repos/coder/vscode-coder/src/workspacesProvider.ts
./src/workspacesProvider.ts 251:20-28
[tsl] ERROR in /Users/matifali/repos/coder/vscode-coder/src/workspacesProvider.ts(251,21)
TS2339: Property 'statuses' does not exist on type 'WorkspaceApp'.
@ ./src/extension.ts 47:29-60
ERROR in /Users/matifali/repos/coder/vscode-coder/src/workspacesProvider.ts
./src/workspacesProvider.ts 251:36-44
[tsl] ERROR in /Users/matifali/repos/coder/vscode-coder/src/workspacesProvider.ts(251,37)
TS2339: Property 'statuses' does not exist on type 'WorkspaceApp'.
@ ./src/extension.ts 47:29-60
ERROR in /Users/matifali/repos/coder/vscode-coder/src/workspacesProvider.ts …
```

Revert "chore: update Node.js version to 20"

---

.github/dependabot.yml
.github/workflows/ci.yaml
package.json

This version must match the version in coder/coder. @aqandrew and dependabot mistakenly upgraded this version. (not mad, just letting you know)
I've updated dependabot's config to avoid it updating it to begin with, and added a build check to CI so that we can have better confidence in the build-ability of the main branch.

chore: downgrade ua-parser-js version

---

CHANGELOG.md
src/api.ts
src/headers.ts
src/remote.ts
src/util.ts

Closes #499
The `coder start` command can't always work properly without specifying these args (eg., getting past proxies). This refactors the code a little to make it easier to get the right argument values, and passes them to `coder start`.

fix: specify `--header-command` when running `coder start`

---

src/remote.ts

feat: handle windows specific paths in log-path parameter

---

CHANGELOG.md
src/commands.ts
src/extension.ts

This change allows `localWorkspaceFolder` and `localConfigFile` to be
provided which allows us to use `dev-container` rather than
`attached-container` to enter enabling all dev container features like
file change detection and rebuilding.
Example open URL:
```
vscode://coder.coder-remote/openDevContainer?owner=mafredri&workspace=magenta-rat-8&agent=dev&devContainerName=boring_shaw&devContainerFolder=/workspaces/coder&localWorkspaceFolder=/home/coder/coder&localConfigFile=/home/coder/coder/.devcontainer/devcontainer.json
```

fix: improve `openDevContainer` support with local workspace folder

---

CHANGELOG.md
src/commands.ts
src/workspacesProvider.ts

#121 
This change updates the behavior when opening a workspace from the sidebar: the first agent is now opened automatically using the same remote authority URI as when opening the agent directly.
If a workspace has multiple agents, we always open the first one, skipping the agent selection QuickPick when the folder is opened. I implemented it this way since we're already opening the `folderPath` of the first agent by default.
If this behavior should only apply when there's a single agent, it's easy to adjust. But in that case, should we also avoid passing the `folderPath` when multiple agents are present?

Use primary agent for the remote authority when opening a workspace

---

src/storage.ts

Use truncated version with signature fallback

---

CHANGELOG.md
src/commands.ts
src/remote.ts

Enable verbose output when setting a log directory

---

CHANGELOG.md
src/commands.ts
src/extension.ts
src/remote.ts
src/storage.ts

Automatically start workspace when explicitly opening

---

package.json
src/extension.ts
src/workspace/workspacesProvider.ts

Fixes #330
Adds a search filter for both views "My Workspaces" and "All Workspaces", this depends on the VS Code command `list.find` so support fuzzy match and filtering but does not differentiate between nodes (so we filter on everything not just workspaces or agents... etc).
Also, I have add `id`s to all tree items, this guarantees that the expansion state stays the same between refreshes.
One downside to using this method is that whenever the tree view refreshes (which is every ~1s) the focus is shifted to the tree instead of the input. I tried to implement selective refreshing such that we refresh only the affected nodes but that didn't fix it :/. See:
https://github.com/user-attachments/assets/ede5b005-a19b-4d48-8fe5-7db6df83652b

Add search filter to Coder Workspaces tree views

---

.eslintrc.json
src/commands.ts
src/core/container.ts
src/core/contextManager.ts
src/core/secretsManager.ts
src/error.ts
src/extension.ts
src/remote/remote.ts
src/workspace/workspaceMonitor.ts
test/mocks/testHelpers.ts
test/unit/core/secretsManager.test.ts

Improve consistency in client-side login/logout experience

---

CHANGELOG.md
src/api/coderApi.ts
src/core/cliManager.ts
src/logging/formatters.ts
src/logging/httpLogger.ts
src/logging/types.ts
src/logging/utils.ts
src/logging/wsLogger.ts
test/mocks/testHelpers.ts
test/unit/core/cliManager.test.ts
test/unit/logging/formatters.test.ts
test/unit/logging/httpLogger.test.ts
test/unit/logging/utils.test.ts
test/unit/logging/wsLogger.test.ts

Fix JSON stringify circular structure when logging
